name: theming
description: A new Flutter package project.
version: 0.0.1
author: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0-nullsafety.0
  freezed_annotation: ^0.13.0-nullsafety.0
  google_fonts: ^2.0.0-nullsafety.0
  shared_preferences: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  freezed: ^0.14.0-nullsafety.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
