name: theming
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  freezed_annotation: ^2.0.0
  google_fonts: ^3.0.1
  collection: ^1.16.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^2.0.1
  freezed: ^2.0.0
  all_lint_rules_community: ^0.0.17
