name: theming
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  freezed_annotation: ^1.1.0
  google_fonts: ^2.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^1.0.3
  freezed: ^1.1.0
