name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  android_intent_plus: ^3.0.1
  animations: ^2.0.0
  async: ^2.4.2
  collection: ^1.15.0
  contacts_service:
    git: https://github.com/gaetschwartz/flutter_contacts.git
  cross_file: ^0.3.3+2
  cupertino_icons: ^1.0.0
  file: ^6.0.0
  firebase_core: ^2.1.1
  flex_color_scheme: ^6.0.1
  fluentui_system_icons: ^1.1.136
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.0
  gaets_logging:
    path: ../packages/logging
  gap: ^2.0.0
  geolocator: ^9.0.0
  google_fonts: ^3.0.1
  hive: ^2.0.0
  http: ^0.13.3
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.2.3+7
  in_app_purchase_storekit: ^0.3.3
  intl: ^0.17.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  json_annotation: ^4.0.0
  live_route:
    path: ../packages/live_route/
  meta: ^1.3.0
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: d3779be7d661481cc0d99090d6356a286ae4f86b
      path: modal_bottom_sheet
  octo_image: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  process_run: ^0.12.0
  quick_actions: ^1.0.0
  scrollable_positioned_list: ^0.3.0
  share_plus: ^6.0.1
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  theming:
    path: ../packages/theming
  url_launcher: ^6.0.0
  url_strategy: ^0.2.0
  vibration:
    path: ../packages/vibration
  xml: ^6.1.0
  xml2json: ^5.3.2

dev_dependencies:
  all_lint_rules_community: ^0.0.15
  build_runner: ^2.0.1
  dart_code_metrics: ^5.0.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  integration_test:
    sdk: flutter
  isar_generator: ^3.0.2
  json_serializable: ^6.1.3
  lint: ^1.1.1
  mockito: ^5.0.0-nullsafety.1

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/profiles/
    - assets/pictures/
    - assets/config.json
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: false
  image_path: "lib/logo/swift-white.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/logo/swift.png"

flutter_intl:
  enabled: false
  use_deferred_loading: true
