name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=3.0.0-0.0.beta <4.0.0"

dependencies:
  android_intent_plus: ^4.0.0
  animations: ^2.0.0
  async: ^2.4.2
  collection: ^1.15.0
  contacts_service:
    git:
      url: https://github.com/gaetschwartz/flutter_contacts.git
      ref: 21ecb33d5bf6f19776cc8466db2437a6e5600703

  cross_file: ^0.3.3+2
  cupertino_icons: ^1.0.0
  file: ^6.0.0
  flex_color_scheme: ^7.0.0
  fluentui_system_icons: ^1.1.136
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.0
  gaets_logging:
    git:
      url: https://github.com/gaetschwartz/gaet_utils.git
      path: packages/logging
  gap: ^3.0.0
  geolocator: ^9.0.0
  google_fonts: ^4.0.3
  hive: ^2.0.0
  http: ^0.13.3
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.3.0+4
  in_app_purchase_storekit: ^0.3.3
  intl: ^0.18.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  json_annotation: ^4.0.0
  live_route:
    path: ../packages/live_route/
  meta: ^1.3.0
  modal_bottom_sheet: ^3.0.0-pre
  octo_image: ^1.0.0
  package_info_plus: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  process_run: ^0.13.0
  quick_actions: ^1.0.0
  riverpod_annotation: ^2.0.0
  scrollable_positioned_list: ^0.3.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.0
  shimmer: ^3.0.0
  theming:
    git:
      url: https://github.com/gaetschwartz/gaet_utils.git
      path: packages/theming
  url_launcher: ^6.0.0
  url_strategy: ^0.2.0
  vibration:
    git:
      url: https://github.com/gaetschwartz/gaet_utils.git
      path: packages/vibration
  xml: ^6.1.0
  xml2json: ^6.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.15
  build_runner: ^2.0.1
  custom_lint: ^0.4.0
  dart_code_metrics: ^5.2.1
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  integration_test:
    sdk: flutter
  isar_generator: ^3.0.2
  json_serializable: ^6.1.3
  lint: ^2.0.1
  mockito: ^5.0.0
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/profiles/
    - assets/pictures/
    - assets/config.json

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "lib/logo/swift-white.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/logo/swift.png"

flutter_intl:
  enabled: false
  use_deferred_loading: true
