name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  live_route:
    path: ../packages/live_route/
  theming:
    path: ../packages/theming
  vibration:
    path: ../packages/vibration
  gaets_logging:
    path: ../packages/logging
  android_intent: ^2.0.0
  animations: ^2.0.0
  async: ^2.4.2
  collection: ^1.15.0
  cupertino_icons: ^1.0.0
  file: ^6.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0
  flex_color_scheme: ^3.0.1
  flutter_riverpod: ^0.14.0+1
  flutter_slidable: ^0.6.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.0
  geolocator: ^7.0.1
  google_fonts: ^2.0.0
  hive: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  octo_image: ^1.0.0
  path_provider: ^2.0.0
  process_run: ^0.12.0
  quick_actions: ^0.6.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ^2.0.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.0
  url_strategy: ^0.2.0
  contacts_service:
    git: https://github.com/gaetschwartz/flutter_contacts.git
  permission_handler: ^8.1.4+2
  fluttercontactpicker: ^4.5.1
  fluentui_system_icons: ^1.1.136

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_lints: ^1.0.3
  freezed: ^0.14.0-nullsafety.0
  json_serializable: ^5.0.0
  lint: ^1.1.1
  mockito: ^5.0.0-nullsafety.1
  dart_code_metrics: ^4.2.1

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/profiles/
    - assets/anims/
    - assets/pictures/
    - assets/config.json
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: false
  image_path: "lib/logo/swift-white.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/logo/swift.png"

flutter_intl:
  enabled: false
  use_deferred_loading: true
